name: build

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        java-version: 25
        distribution: temurin
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Setup SAM
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true
    - name: Build
      run: sam build --debug
    - name: Generate code coverage report
      run: ./gradlew jacocoTestReport
    - name: Upload code coverage report
      uses: qltysh/qlty-action/coverage@v2
      env:
        JACOCO_SOURCE_PATH: lambda/src/main/java
      with:
        token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
        files: lambda/build/reports/jacoco/test/jacocoTestReport.xml
